name: feeds

on:
  workflow_dispatch:
  schedule:
    - cron: 30 */4 * * *

jobs:
  feeds:
    uses: ./.github/workflows/_sync.yml
    permissions:
      contents: write
    secrets:
      base-url: https://feed.phenx.de/lootscraper_
      base-directory: feeds
